// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjGUjNQ5mVBvoTSl0fYHPGk622TnYq46g',
    appId: '1:283488801219:web:712d59aebe41863f48ad76',
    messagingSenderId: '283488801219',
    projectId: 'firstapp-f9497',
    authDomain: 'firstapp-f9497.firebaseapp.com',
    storageBucket: 'firstapp-f9497.firebasestorage.app',
    measurementId: 'G-RP9B8N4P9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIhylQEf5T6f8dBs-WgqbUgXX5dID7gpE',
    appId: '1:283488801219:android:adccaf8932925b4d48ad76',
    messagingSenderId: '283488801219',
    projectId: 'firstapp-f9497',
    storageBucket: 'firstapp-f9497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb-sZQ6ghMPIv513EudaTbk0JDVpbT7nM',
    appId: '1:283488801219:ios:77b55b18f3f8c3ca48ad76',
    messagingSenderId: '283488801219',
    projectId: 'firstapp-f9497',
    storageBucket: 'firstapp-f9497.firebasestorage.app',
    iosBundleId: 'com.example.personalitytest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb-sZQ6ghMPIv513EudaTbk0JDVpbT7nM',
    appId: '1:283488801219:ios:77b55b18f3f8c3ca48ad76',
    messagingSenderId: '283488801219',
    projectId: 'firstapp-f9497',
    storageBucket: 'firstapp-f9497.firebasestorage.app',
    iosBundleId: 'com.example.personalitytest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjGUjNQ5mVBvoTSl0fYHPGk622TnYq46g',
    appId: '1:283488801219:web:6359dd4ce1f6c9ce48ad76',
    messagingSenderId: '283488801219',
    projectId: 'firstapp-f9497',
    authDomain: 'firstapp-f9497.firebaseapp.com',
    storageBucket: 'firstapp-f9497.firebasestorage.app',
    measurementId: 'G-7F6Q902PEJ',
  );
}
